# Generated by Django 5.0.6 on 2024-08-01 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_calculator1', '0002_splited_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trip_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
