# Generated by Django 5.0.6 on 2024-08-01 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip_calculator1', '0003_trip_trip_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
